config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'

  # Main routes
  resources :users # ADD `, :only => [:new, :create, :index]` to this once tested to limit ability for users to input into database
  resources :shits # gets all available routes for Shits
  resources :comments # gets all available routes for Comments
  resources :likes # gets all available routes for Likes

  delete '/' => 'likes#destroy'

  post '/' => 'pages#clipboard'

  # Login feature
  get '/login' => 'session#new' # login form
  post '/login' => 'session#create' # process the login
  delete '/login' => 'session#destroy' # log out

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beet.rb
class Beet < ApplicationRecord
  belongs_to :user, :optional => true
  has_many :likes
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :shit, :optional => true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :shit, :optional => true
end

app/models/shit.rb
class Shit < ApplicationRecord
  belongs_to :user, :optional => true
  has_many :likes
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :shits
  has_many :comments
  has_many :likes
  has_secure_password
  validates :username, :uniqueness => true, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user # checks

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current.user.present?
  end

  def check_for_admin
    redirect_to root_path unless @current_user.present? && @current_user.admin?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end


  def new
    @comment = Comment.new
  end

  def create
    comment = Comment.create comment_params
    redirect_to request.referrer
  end

  def destroy
    shit = params[:shit_id]
    user = params[:user_id]
    comment_id = params[:id]
    comment = Comment.where(id: comment_id, shit_id: shit, user_id: user)
    comment.destroy_all
    redirect_to request.referrer
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :shit_id, :user_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @likes = Like.all
  end

  def new
    @shits = Shit.all
    @likes = Like.all
    @like = Like.new
  end

  def create
    @likes = Like.all
    like = Like.create like_params
    shit = like.shit
    redirect_to root_path(anchor: "#{shit.id}")
  end

  def show
  end

  def destroy
    shit = params[:shit_id]
    user = params[:user_id]
    like = Like.where(shit_id: shit, user_id: user)
    like.destroy_all
    redirect_to root_path(anchor: shit)
  end

  private
  def like_params
    params.require(:like).permit(:shit_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @shits = Shit.all
    @likes = Like.all
    @comments = Comment.all
    @like_new = Like.new
  end

  def clipboard
    shit = Shit.find params[:id]
    IO.popen("pbcopy", "w") { |clipboard| clipboard.puts shit.content }
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :username => params[:username]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id # only search for user_id for efficiency-sake
      redirect_to root_path
    else
      flash[:error] = "Invalid username or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/shits_controller.rb
class ShitsController < ApplicationController

  def index
    @shits = Shit.all
  end

  def new
    @shit = Shit.new
  end

  def create
    shit = Shit.create :title => params[:shit][:title], :tags => params[:shit][:tags], :user_id => @current_user.id
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      shit.image = req["public_id"] # store the Cloudinary link in the image column
      shit.content = AsciiGen.new(Cloudinary::Utils.cloudinary_url(req["public_id"])).to_ascii_art(width: 70)
      shit.save
    end
    redirect_to root_path # show the shit detail page
  end

  def edit
    @shit = Shit.find params[:id]
  end

  def update
    shit = Shit.find params[:id]
    shit.update shit_params
    redirect_to shit # redirect back to the shit page
  end

  def show
    @shit = Shit.find params[:id]
    @user = @shit.user
    @comments = @shit.comments
    @comment_new = Comment.new
    @likes = Like.all
    @like_new = Like.new
  end

  def destroy
    shit = Shit.find params[:id]
    shit.destroy
    redirect_to root_path # redirect back to the index
  end

  def clipboard
    shit = Shit.find params[:id]
    IO.popen("pbcopy", "w") { |clipboard| clipboard.puts shit.content }
  end

  private
  def shit_params # setup of strong params
    params.require(:shit).permit(:title, :tags, :content, :image, :like_count, :comment_count, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params # save user as an object before it's written to the server to check for duplicate submissions or other errors with the form
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.update user_params
    redirect_to user
  end

  def show
    @user = User.find params[:id]
    @shits = Shit.all
    @likes = Like.all
    @like_new = Like.new
    @comments = Comment.all
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:username, :bio, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commenrs_helper.rb
module CommenrsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/shits_helper.rb
module ShitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beets/_form.html.erb
<%= form_for(@beet, :html => {:multipart => true}) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :tags %>
  <%= f.text_field :tags %>
  <%= f.label "Image to convert" %>
  <%= f.cl_image_upload :image, :class => "custom-file-input", :required => true %>
  <%= f.submit %>
<% end %>

app/views/beets/edit.html.erb
<h1>Edit your Beet!</h1>

<%= render :partial => 'form' %>

app/views/beets/new.html.erb
<div class="page-container">

  <h1>Create a Beet!</h1>

  <%= render :partial => 'form' %>

</div>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/likes/edit.html.erb
<h1>Likes#edit</h1>
<p>Find me in app/views/likes/edit.html.erb</p>

app/views/likes/new.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/show.html.erb
<h1>Likes#show</h1>
<p>Find me in app/views/likes/show.html.erb</p>

app/views/session/_form.html.erb
<% if flash[:error].present? %>
  <p class="error">
    <%= flash[:error] %>
  </p>
<% end %>

<%= form_tag login_path do %>
  <%= label_tag :username %>
  <%= username_field_tag :username  %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag "sign in" %>
<% end %>

app/views/session/new.html.erb
<div class="page-container">

  <h1>sign in</h1>

  <%= render :partial => 'form' %>

  <div class="info-container">

    <p>don't have an account? sign up <%= link_to "here", new_user_path %>.</p>

  </div>

</div>

app/views/shits/_form.html.erb
<%= form_for(@shit, :html => {:multipart => true}) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :tags %>
  <%= f.text_field :tags %>
  <%= f.label "Image to convert" %>
  <%= f.cl_image_upload :image, :class => "custom-file-input", :required => true %>
  <%= f.submit %>
<% end %>

app/views/shits/edit.html.erb
<h1>Edit your Shit!</h1>

<%= render :partial => 'form' %>

app/views/shits/index.html.erb
<h1>All Shits</h1>

<% @shits.each do |shit| %>
  <p><%= link_to cl_image_tag(shit.image, :alt => shit.user.username), shit %></p>
<% end %>

app/views/shits/new.html.erb
<div class="page-container">

  <h1>Create a Shit!</h1>

  <%= render :partial => 'form' %>

</div>

app/views/shits/show.html.erb
<h1><%= @shit.title %></h1>

<% if @current_user.present? %>

  <% if @current_user.id == @user.id || @current_user.admin? %>

    <div class="controls">
      <%= link_to 'edit post', edit_shit_path(@shit) %>
      <%= link_to 'delete shit', @shit, :method => 'delete' %>
    </div>

  <% end %>

<% end %>

<div class="post">

  <pre><%= @shit.content %></pre>

  <div class="info">

    <a href="/users/<%= @shit.user_id %>" class="info-item"><%= @shit.user.username %></a>

    <% if @current_user.present? %>

      <% if @likes.where(user_id: @current_user.id, shit_id: @shit.id).any? == true %>

        <%= link_to "♥ #{ @likes.where(shit_id: @shit.id).count }", root_path(:user_id => @current_user.id, :shit_id => @shit.id), :id => "liked", :method => 'delete' %>

      <% else %>

        <p>
          <%= form_for @like_new do |f| %>
            <%= f.hidden_field :shit_id, value: @shit.id %>
            <%= f.hidden_field :user_id, value: @current_user.id %>
            <%= f.submit "♡ #{@likes.where(shit_id: @shit.id).count}", :id => "like" %>
          <% end %>
        </p>

      <% end %>

    <% else %>

      <%= link_to "♡ #{@likes.where(shit_id: @shit.id).count}", login_path, :id => "like" %>

    <% end %>

    <div class="tooltip">
      <%= link_to "", root_path(:id => @shit.id), :class => 'far fa-copy', :id => 'clipboard', :method => 'clipboard' %><span class="tooltiptext">Copy to clipboard</span>
    </div>

  </div>

</div>

<h2>Comments <%= "[#{ @comments.where(shit_id: @shit.id).count }]" %></h2>

<% @comments.each do |comment| %>
  <div class="comments" id="<%= comment.id %>">
    <p><%= comment.content %></p>
    <div class="comments-info">
      <a href="/users/<%= comment.user.id %>"><%= comment.user.username %></a>
      <% if @current_user.present? && @current_user.id == comment.user.id %>
        <%= link_to 'delete comment', comment_path(:id => comment.id, :user_id => @current_user.id, :shit_id => @shit.id), :class => 'delete-comment', :method => 'delete' %>
      <% end %>
    </div>
  </div>
<% end %>

<% if @current_user.present? %>
  <div class="leave-comment">
    <h3>Comment on <%= @shit.user.username %>'s shit:</h3>
    <%= form_for @comment_new do |f| %>
      <%= f.text_field :content %>
      <%= f.hidden_field :shit_id, value: @shit.id %>
      <%= f.hidden_field :user_id, value: @current_user.id %>
      <%= f.submit "leave comment" %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @user do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username, :maxlength => 18, :required => true %>

  <%= f.label :bio %>
  <%= f.text_field :bio %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :required => true %>

  <%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<div class="page-container">

<%= render :partial => 'form'  %>

</div>

app/views/users/index.html.erb
<h1>All Users for testing</h1>

<% @users.each do |user| %>
  <%= link_to user.username, user %>
<% end %>

app/views/users/new.html.erb
<div class="page-container">

  <h1>Create new user</h1>

  <%= render :partial => 'form'  %>

  <div class="info-container">

    <p>already have an account? log in <%= link_to "here", login_path %>.</p>

  </div>

</div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<div class="controls">

  <% if @current_user.present? && @current_user.id == @user.id %>
    <%= link_to 'edit profile', edit_user_path %>
  <% end %>

  <% if @user.bio.present? %>
    <p><%= @user.bio %></p>
  <% end %>

</div>

<div class="post-container">

  <% @shits.order('created_at DESC').each do |shit| %>

    <% if shit.user_id == @user.id %>

      <div class="post">

        <pre><%= shit.content %></pre>

        <div class="info">

          <a href="/users/<%= shit.user_id %>" class="info-item"><%= shit.user.username %></a>

          <% if @current_user.present? %>

            <% if @likes.where(user_id: @current_user.id, shit_id: shit.id).any? == true %>

              <%= link_to "♥ #{ @likes.where(shit_id: shit.id).count }", root_path(:user_id => @current_user.id, :shit_id => shit.id), :id => "liked", :method => 'delete' %>

            <% else %>

              <p>
                <%= form_for @like_new do |f| %>
                  <%= f.hidden_field :shit_id, value: shit.id %>
                  <%= f.hidden_field :user_id, value: @current_user.id %>
                  <%= f.submit "♡ #{@likes.where(shit_id: shit.id).count}", :id => "like" %>
                <% end %>
              </p>

            <% end %>

          <% else %>

            <%= link_to "♡ #{@likes.where(shit_id: shit.id).count}", login_path, :id => "like" %>

          <% end %>

          <a href="/shits/<%= shit.id %>" id="comment-shit" class="info-item">comments <%= "[#{@comments.where(shit_id: shit.id).count}]" if @comments.where(shit_id: shit.id).count != 0 %></a>

          <div class="tooltip">
            <%= link_to "", root_path(:id => shit.id), :class => 'far fa-copy', :id => 'clipboard', :method => 'clipboard' %><span class="tooltiptext">Copy to clipboard</span>
          </div>

        </div>

      </div>

    <% end %>

  <% end %>

</div>