config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'

  # Main routes
  resources :users # ADD `, :only => [:new, :create, :index]` to this once tested to limit ability for users to input into database
  resources :shits # gets all available routes for Shits
  resources :comments # gets all available routes for Comments
  resources :likes # gets all available routes for Likes

  delete '/' => 'likes#destroy'

  post '/' => 'pages#clipboard'

  # Login feature
  get '/login' => 'session#new' # login form
  post '/login' => 'session#create' # process the login
  delete '/login' => 'session#destroy' # log out

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beet.rb
class Beet < ApplicationRecord
  belongs_to :user, :optional => true
  has_many :likes
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :shit, :optional => true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :shit, :optional => true
end

app/models/shit.rb
class Shit < ApplicationRecord
  belongs_to :user, :optional => true
  has_many :likes
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :shits
  has_many :comments
  has_many :likes
  has_secure_password
  validates :username, :uniqueness => true, :presence => true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end


  def new
    @comment = Comment.new
  end

  def create
    comment = Comment.create comment_params
    redirect_to request.referrer
  end

  def destroy
    shit = params[:shit_id]
    user = params[:user_id]
    comment_id = params[:id]
    comment = Comment.where(id: comment_id, shit_id: shit, user_id: user)
    comment.destroy_all
    redirect_to request.referrer
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :shit_id, :user_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @likes = Like.all
  end

  def new
    @shits = Shit.all
    @likes = Like.all
    @like = Like.new
  end

  def create
    @likes = Like.all
    like = Like.create like_params
    shit = like.shit
    redirect_to root_path(anchor: "#{shit.id}")
  end

  def show
  end

  def destroy
    shit = params[:shit_id]
    user = params[:user_id]
    like = Like.where(shit_id: shit, user_id: user)
    like.destroy_all
    redirect_to root_path(anchor: shit)
  end

  private
  def like_params
    params.require(:like).permit(:shit_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @shits = Shit.all
    @likes = Like.all
    @comments = Comment.all
    @like_new = Like.new
  end

  def clipboard
    shit = Shit.find params[:id]
    IO.popen("pbcopy", "w") { |clipboard| clipboard.puts shit.content }
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :username => params[:username]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id # only search for user_id for efficiency-sake
      redirect_to root_path
    else
      flash[:error] = "Invalid username or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/shits_controller.rb
class ShitsController < ApplicationController

  def index
    @shits = Shit.all
  end

  def new
    @shit = Shit.new
  end

  def create
    shit = Shit.create :title => params[:shit][:title], :tags => params[:shit][:tags], :user_id => @current_user.id
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      shit.image = req["public_id"] # store the Cloudinary link in the image column
      shit.content = AsciiGen.new(Cloudinary::Utils.cloudinary_url(req["public_id"])).to_ascii_art(width: 70)
      shit.save
    end
    redirect_to root_path # show the shit detail page
  end

  def edit
    @shit = Shit.find params[:id]
  end

  def update
    shit = Shit.find params[:id]
    shit.update shit_params
    redirect_to shit # redirect back to the shit page
  end

  def show
    @shit = Shit.find params[:id]
    @user = @shit.user
    @comments = @shit.comments
    @comment_new = Comment.new
    @likes = Like.all
    @like_new = Like.new
  end

  def destroy
    shit = Shit.find params[:id]
    shit.destroy
    redirect_to root_path # redirect back to the index
  end

  def clipboard
    shit = Shit.find params[:id]
    IO.popen("pbcopy", "w") { |clipboard| clipboard.puts shit.content }
  end

  private
  def shit_params # setup of strong params
    params.require(:shit).permit(:title, :tags, :content, :image, :like_count, :comment_count, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params # save user as an object before it's written to the server to check for duplicate submissions or other errors with the form
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.update user_params
    redirect_to user
  end

  def show
    @user = User.find params[:id]
    @shits = Shit.all
    @likes = Like.all
    @like_new = Like.new
    @comments = Comment.all
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:username, :bio, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commenrs_helper.rb
module CommenrsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/shits_helper.rb
module ShitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>ASCII Hunt (o˘◡˘o)</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= cloudinary_js_config %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" async />

    <%= favicon_link_tag asset_path('favicon.png') %>

    <meta property="og:title" content="ASCII Hunt (o˘◡˘o)" />
    <meta property="og:description" content="Create your own ASCII Masterpiece by uploading an image and watch it come to life in ASCII!" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://asciihunt.indiealistic.studio/" />
    <%= tag :meta, property: 'og:image', content: image_url('asciihunt-og.png') %>

  </head>

  <body>

    <nav>

      <ul>

        <li><%= link_to 'ASCII Hunt', root_path, :class => 'title' %></li>
        <li><%= link_to 'feed', root_path, :class => 'nav-item' %></li>
        <% if @current_user.present? %>
          <li><a href="/users/<%= @current_user.id %>"><%= "view profile" %></a></li>
          <% if @current_user.admin? %>
            <li><%= link_to 'users (admin only)', users_path %></li>
          <% end %>
          <li><%= link_to "log out", login_path, :class => 'nav-item', :method => 'delete' %></li>
          <li><%= link_to "create shit!", new_shit_path, :class => 'create-shit' %></li>
        <% else %>
          <li><%= link_to 'sign up', new_user_path %></li>
          <li><%= link_to 'login', login_path %></li>
          <li><%= link_to "create shit!", login_path, :class => 'create-shit' %></li>
        <% end %>

      </ul>

    </nav>

    <div class="main-container">

      <%= yield %>

    </div>

    <div class="credits">brought to you in <%= Date.current.year %> by <a href="https://indiealistic.studio" target="_blank">indiealistic</a>. made possible with <a href="https://cloudinary.com" target="_blank">Cloudinary</a> and <a href="https://heroku.com" target="_blank">Heroku</a>.</div>

  </body>
</html>

app/views/pages/home.html.erb
<div class="post-container">

  <% @shits.order('created_at DESC').each do |shit| %>

    <div class="post" id="<%= shit.id %>">

      <pre><%= shit.content %></pre>

      <div class="info">

        <a href="/users/<%= shit.user_id %>" class="info-item"><%= shit.user.username %></a>

        <% if @current_user.present? %>

          <% if @likes.where(user_id: @current_user.id, shit_id: shit.id).any? == true %>

            <%= link_to "♥ #{ @likes.where(shit_id: shit.id).count }", root_path(:user_id => @current_user.id, :shit_id => shit.id), :id => "liked", :method => 'delete' %>

          <% else %>

            <p>
              <%= form_for @like_new do |f| %>
                <%= f.hidden_field :shit_id, value: shit.id %>
                <%= f.hidden_field :user_id, value: @current_user.id %>
                <%= f.submit "♡ #{@likes.where(shit_id: shit.id).count}", :id => "like" %>
              <% end %>
            </p>

          <% end %>

        <% else %>

          <%= link_to "♡ #{@likes.where(shit_id: shit.id).count}", login_path, :id => "like" %>

        <% end %>

        <a href="/shits/<%= shit.id %>" id="comment-shit" class="info-item">comments <%= "[#{@comments.where(shit_id: shit.id).count}]" if @comments.where(shit_id: shit.id).count != 0 %></a>

        <div class="tooltip">
          <%= link_to "", root_path(:id => shit.id), :class => 'far fa-copy', :id => 'clipboard', :method => 'clipboard' %><span class="tooltiptext">Copy to clipboard</span>
        </div>

      </div>

    </div>

  <% end %>

</div>